### Health check
GET http://localhost:3333/health

### List products (opcional: ?search=nome)
GET http://localhost:3333/products

### Create product
POST http://localhost:3333/products
Content-Type: application/json

{
    "nome": "Produto dois ",
    "descricao": "OUTRO produto para testar",
    "preco": 22.9,
    "quantidade": 5,
    "categoria": "demo",
    "ativo": true
}

### Get product by id (substitua :id)
GET http://localhost:3333/products/8a9a9ee1-5306-4a23-a76d-6e334cfbe071

### Update product
PUT http://localhost:3333/products/8a9a9ee1-5306-4a23-a76d-6e334cfbe071
Content-Type: application/json

{
    "nome": "Produto Demo Atualizado",
    "descricao": "Atualizado",
    "preco": 24.5,
    "quantidade": 8,
    "categoria": "demo",
    "ativo": true
}

### Delete product
DELETE http://localhost:3333/products/8a9a9ee1-5306-4a23-a76d-6e334cfbe071
